version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "9000:3000"
    networks:
      - monitoring

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6db
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_USER=k6user
      - INFLUXDB_USER_PASSWORD=k6pass
    networks:
      - monitoring

#  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus:/etc/prometheus
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    networks:
#      - monitoring

#  k6-prometheus-exporter:
#    image: loadimpact/k6-prometheus-exporter:latest
#    ports:
#      - "3030:3030"
#    networks:
#      - monitoring
#    environment:
#      - K6_PROMETHEUS_ADDRESS=:3030

networks:
  monitoring: